spring:
#  disable service discovery
  cloud:
    config:
      discovery:
        enabled: false
  datasource:
    username: inventory_service
    password: password
    url: jdbc:mysql://127.0.0.1:3306/inventoryservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC